# Generated by Django 3.0.5 on 2020-04-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gpu',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='GPU_Annotation',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='GPU_Name',
            new_name='title',
        ),
    ]
