# Generated by Django 3.0.5 on 2020-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200430_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='image',
            field=models.CharField(default='image', max_length=200),
        ),
        migrations.AddField(
            model_name='gpu',
            name='link',
            field=models.CharField(default='link', max_length=200),
        ),
        migrations.AddField(
            model_name='gpu',
            name='price',
            field=models.CharField(default='price', max_length=50),
        ),
    ]
