# Generated by Django 3.0.5 on 2020-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200507_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(default='link', max_length=200)),
                ('price', models.CharField(default='price', max_length=50)),
                ('image', models.CharField(default='image', max_length=200)),
                ('annotation', models.CharField(max_length=1000)),
            ],
        ),
    ]
