# Generated by Django 3.0.5 on 2020-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_motherboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='brand_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='brand_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='processor',
            name='brand_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
